// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAy_VYYp0ukgc6IDIu9Y0CiXV03938nJE',
    appId: '1:448066146222:web:a3ea36f576bcc7a861c23f',
    messagingSenderId: '448066146222',
    projectId: 'eventapp1-b8512',
    authDomain: 'eventapp1-b8512.firebaseapp.com',
    storageBucket: 'eventapp1-b8512.appspot.com',
    measurementId: 'G-46D6KV4HFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTeg5zy-d0XI1ZUooMTOrzVVI5UpNgaIk',
    appId: '1:448066146222:android:f36c7dcbb30b669461c23f',
    messagingSenderId: '448066146222',
    projectId: 'eventapp1-b8512',
    storageBucket: 'eventapp1-b8512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1bLwJid12Uo5f9Mw1_Gt91mAA2vGOPQ',
    appId: '1:448066146222:ios:e6a84aadf7c4d4a461c23f',
    messagingSenderId: '448066146222',
    projectId: 'eventapp1-b8512',
    storageBucket: 'eventapp1-b8512.appspot.com',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1bLwJid12Uo5f9Mw1_Gt91mAA2vGOPQ',
    appId: '1:448066146222:ios:1647ead048fc5a6161c23f',
    messagingSenderId: '448066146222',
    projectId: 'eventapp1-b8512',
    storageBucket: 'eventapp1-b8512.appspot.com',
    iosBundleId: 'com.example.eventapp.RunnerTests',
  );
}
